### ISSUE TITLE
Features and plans (roadmap)

### ISSUE THREAD

**Issue by Mr-Auto** [zappatic/Spelunky2X64DbgPlugin#66]
Features and upgrades i would like to implement in the future
Feel free to add suggestions or disuse anything listed here. If you want to help with anything, let me know

Github:
- [x] Use cache to store the QT instead of downloading it every time
- [x] Add PR checks (build and formatting?)
- [x] Add json parser/validator

Implementing standard library structs (and other):
- [x] std::map and std::set
- [ ] std::list
- [x] std::string
- [ ] std::unordered_map and std::unordered_set
- [ ] EntityList (changing the current Vector type to View)
- [ ] Static arrays
- [ ] Add GameAPI view

Improvements:
- [ ] Add pointer option to fields to not have to add same thing twice (like "StdMap" and "PointerToStdMap"), maybe even getting rid of the `inline_struct_types` and `pointer_types` arrays entirely
- [ ] Refactor `Spelunky2.json` - take all the entity classes, `entity_class_hierarchy` and `default_entity_types` to a separate file. (maybe split even more if that would still be a large file)
- [ ] Implement pagination for big containers

Fixes and optimizations:
- [ ] Parsing json errors display only once right now - if you have more than one error in the json file, you fix it and use "Reload JSON" it won't show the message box again nor will it print the error in log
- [ ] Optimize the level view for entities
- [ ] Theme info in state - display hex value
- [ ] Limit the max size of entity in the entity memory tab
- [ ] Look at the build in types like `EntityPointer`, `EntityUID`, `EntityDBID` etc. as they seem to cause lag when having a lot of them refresh
- [ ] General code optimizations - reducing the amount of string comparisons (maybe assign id for each field when Parsing the json file, instead of using the field name to get any information on them)
- [ ] Reduce the use of `std::unordered_map`, don't think the code needs dynamically add/remove stuff from them, which is the main point of using unordered_map over other containers, maybe instead implement simple vector_map ?
- [ ] Memory leak? - when opening any window (State, Entities, LevelGen, GameManager etc.) x64dbg seam to accumulate more and more memory and that memory doesn't seam to go down

New functionality:
- [ ] Add option to export/import labels and comments as json file
- [ ] Developer mode/show skips mode

**Comment by zappatic** [comment]
- caching Qt: sure, 'cause the last one failed downloading from sourceforge
- PR checks: ok, there's a clang-format file, you can do a similar thing as prettier for the json file. I mostly have clang-format-on-save in VSCode though, that's why there wasn't automation for that.

STL structs:
 - Vector type to view: do you mean displaying a vector in a separate window? Isn't that already the case?
 
Improvements: 
- Pointer option: not sure what exactly this means, but if it simplifies things and everything works the same, then sure!
- Refactor the json: for sure, this started as a very small project to display State contents, so it wasn't really meant for this big amount of data.

Fixes:
- JSON parsing errors: that does indeed sound like a bug
- reducing string comparisons and unordered_maps: the string comparisons are expensive, not sure about the use of the unordered maps though. Fact is that ramming thousands of rows into a `QTreeView` every 100 milliseconds is quite intense :) It only got slower the more stuff we added over time. Whatever you can do to make it faster is good of course.
- Wasn't aware of any leaks, but that sounds like something is leaking...

**Comment by Mr-Auto** [comment]
> * Vector type to view: do you mean displaying a vector in a separate window? Isn't that already the case?

no, I'm talking about the `Vector` not `StdVector`
![image](https://github.com/spelunky-fyi/Spelunky2X64DbgPlugin/assets/36127424/1cc640c1-9b40-404f-9459-27df141edf32)
This struct is widely used in `state->layers`, but i can't use the current implementation as it would load too many entities, that's why i want to make it into separate view

**Comment by zappatic** [comment]
Ahh yes, that thing. Did we ever figure out what exactly that is, as it's not a `std::vector`? Separate view/window is a good idea indeed.

**Comment by Mr-Auto** [comment]
> Ahh yes, that thing. Did we ever figure out what exactly that is, as it's not a `std::vector`? Separate view/window is a good idea indeed.

Yes we did, well, it's not a standard struct, just something that devs implemented, it's in the json `EntityList`, or you can see some clever implementation of it in overlunky: https://github.com/spelunky-fyi/overlunky/blob/main/src/game_api/layer.hpp#L18

**Comment by MrSoup678** [comment]
github.com/x64dbg/sdk pull returns 404.


```-- CPM: Adding package x64dbg@ (x64dbg_9f9b1ba1c03ffb9dc921b3e1f8615412c65723f5)
MSBuild version 17.6.3+07e294721 for .NET Framework

  Checking Build System
  Performing download step (git clone) for 'x64dbg-populate'
  Cloning into 'x64dbg-src'...
  remote: Repository not found.
  fatal: repository 'https://github.com/x64dbg/sdk.git/' not found
  Cloning into 'x64dbg-src'...
  remote: Repository not found.
  fatal: repository 'https://github.com/x64dbg/sdk.git/' not found
  Cloning into 'x64dbg-src'...
  remote: Repository not found.
  fatal: repository 'https://github.com/x64dbg/sdk.git/' not found
  -- Had to git clone more than once: 3 times.
  CMake Error at x64dbg-subbuild/x64dbg-populate-prefix/tmp/x64dbg-populate-gitclone.cmake:39 (message):
    Failed to clone repository: 'https://github.com/x64dbg/sdk.git'
```
Instead x64dbg hosts new template

**Comment by Mr-Auto** [comment]
> github.com/x64dbg/sdk pull returns 404.
> 
> Instead x64dbg hosts new template

Sorry for late replay: fixed with just hosting the pluginsdk in this repo.
I wanted to get it from github but can't find it, the new plugin template just downloads a file from `sourceforge.net` which feels like step back to me (getting anything from github within github will always be better), it's also another embedded link that who knows if it will last, maybe they will again decide to trash that and suddenly you're project doesn't build again. 
Thou I'm a little bit worried about the QT that they host and we use here

**Comment by Mr-Auto** [comment]
@zappatic I kind of started fixing and changing stuff and ended up rewriting a lot of stuff xd
like getting the Spelunky2 stuff similar as we get state in Overlunky instead of holding pointer somewhere

So before I continue, wanted to ask if it's ok with you, or should i limit myself to the list i made in first post?

**Comment by zappatic** [comment]
> fixed with just hosting the pluginsdk in this repo. 

Agreed completely, best solution in this case.

> Thou I'm a little bit worried about the QT that they host and we use here

If that disappears, at least x64dbg will also have a problem they need to address, as they instruct to download it from a third party on their build instructions as well: https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project
They still link to osdn.net, and it does seem that it starts to download again through that site, where before it didn't.

**Comment by zappatic** [comment]
> @zappatic I kind of started fixing and changing stuff and ended up rewriting a lot of stuff xd like getting the Spelunky2 stuff similar as we get state in Overlunky instead of holding pointer somewhere
> 
> So before I continue, wanted to ask if it's ok with you, or should i limit myself to the list i made in first post?

If it makes things clearer, then sure, go ahead.

**Comment by Mr-Auto** [comment]
Is there a reason for having `Spelunky2Entities.txt` and `Spelunky2ParticleEmitters.txt` as separate files?
don't think anyone would edit those for custom completer or something

Unless the idea was: if the game was updated, it would be quick way for fixing the aliment etc. without building new version. Thou i don't think that's valid anymore

**Comment by zappatic** [comment]
The idea was to separate potentially variable data from the executable, so that people could experiment with it without knowing how to compile the plugin.

**Comment by Mr-Auto** [comment]
> The idea was to separate potentially variable data from the executable, so that people could experiment with it without knowing how to compile the plugin.

They can just input raw number in the filter in db if they want to check "slot" that's not in the list, the only not possible is compare, thou it only maybe makes sense for entities

**Comment by Mr-Auto** [comment]
moved to https://github.com/spelunky-fyi/Spelunky2X64DbgPlugin/issues/2

**Comment by Mr-Auto** [comment]
Moved to https://github.com/spelunky-fyi/Spelunky2X64DbgPlugin/issues/2
